#!/usr/bin/python
import sys
import logging
logging.basicConfig(stream=sys.stderr)
sys.path.insert(0, "/var/www/html2markdown/")  #你app的目录

from main import app as application
application.secret_key = 'Add your secret key'